version: '3.7'

services:
  nginx:
    container_name: nginx 
    restart: always
    image: nginx
    ports:
      - '80:80'
    volumes: 
      - '/opt/compose/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - '/opt/compose/nginx/conf:/etc/nginx/conf.d'
      - '/opt/compose/nginx/html:/usr/share/nginx/html'
      - '/opt/compose/nginx/log:/var/log/nginx'
