version: '3.7'

services:

  # 不同docker需要暴露2888、3888
  # 同一docker可以使用 服务名:2888:3888连接
  # 不同docker使用 主机IP:暴露2888:暴露3888(主机IP可以使用域名代替,需要修改hosts文件)
  # 1号docker zk1 zk2 zk3
  # 2号docker zk4 zk5
  # 3号docker zk6 zk7
  zk6:
    container_name: cluster_multiple_cs3_1
    restart: always
    image: zookeeper
    ports:
      - '32171:2181'
      - '32878:2888'
      - '33878:3888'
    volumes:
      - '/opt/compose/zookeeper/cluster/multiple/cs3/hosts:/etc/hosts'
      - '/opt/compose/zookeeper/cluster/multiple/cs3/zk6/data:/data'
      - '/opt/compose/zookeeper/cluster/multiple/cs3/zk6/log:/datalog'
    environment:
      ZOO_MY_ID: 6
      ZOO_SERVERS: server.1=zk1:12878:13878 server.2=zk2:12868:13868 server.3=zk3:12858:13858 server.4=zk4:22878:23878 server.5=zk5:22868:23868 server.6=zk6:2888:3888 server.7=zk7:2888:3888

  zk7:
    container_name: cluster_multiple_cs3_2
    restart: always
    image: zookeeper
    ports:
      - '32161:2181'
      - '32868:2888'
      - '33868:3888'
    volumes:
      - '/opt/compose/zookeeper/cluster/multiple/cs3/hosts:/etc/hosts'
      - '/opt/compose/zookeeper/cluster/multiple/cs3/zk7/data:/data'
      - '/opt/compose/zookeeper/cluster/multiple/cs3/zk7/log:/datalog'
    environment:
      ZOO_MY_ID: 7
      ZOO_SERVERS: server.1=zk1:12878:13878 server.2=zk2:12868:13868 server.3=zk3:12858:13858 server.4=zk4:22878:23878 server.5=zk5:22868:23868 server.6=zk6:2888:3888 server.7=zk7:2888:3888

  